#!/bin/bash

echo "Setting Railway environment variables via CLI..."
echo ""
echo "First, you need to login to Railway:"
echo "1. Run: railway login"
echo "2. Follow the browser authentication"
echo ""
echo "Then, run these commands in your project directory:"
echo ""
echo "# Link to your Railway project"
echo "railway link"
echo ""
echo "# Set environment variables"
echo "railway variables set DUNE_API_KEY=sim_1IcMrs8pLtODa4izzE7cZAKfaUguj1UF"
echo "railway variables set PORT=\${{PORT}}"
echo ""
echo "# Verify variables are set"
echo "railway variables"
echo ""
echo "# Deploy with the new variables"
echo "railway up"
echo ""
echo "Alternative: If PORT variable is problematic, delete it and let Railway auto-detect:"
echo "railway variables delete PORT"
echo "railway up"